baseURL: https://docs.kanboard.org/
title: Kanboard Documentation
disableKinds: ["RSS", "taxonomy", "term", "sitemap"]
enableRobotsTXT: true

author:
  name: "The Kanboard Authors"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: true

defaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: English
  fr:
    contentDir: content/fr
    title: Documentation de Kanboard
    languageName: Français
  cs:
    contentDir: content/cs
    title: Dokumentace Kanboard
    languageName: čeština
  es:
    contentDir: content/es
    title: Documentación de Kanboard
    languageName: Español
  ru:
    contentDir: content/ru
    title: Канборд Документация
    languageName: Русский
  tr:
    contentDir: content/tr
    title: Kanboard Belgeleri
    languageName: Türk
  pt:
    contentDir: content/pt
    title: Documentação do Kanboard
    languageName: Português
